#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(r8, binding = 0) writeonly uniform image2DArray image;

layout(binding = 1) uniform isampler2DArray diffuse;

void main() {
  vec2 uv = vec2(gl_GlobalInvocationID.xy) / vec2(textureSize(diffuse, 0).xy);
  int color = texture(diffuse, vec3(uv, gl_GlobalInvocationID.z)).r;

  if (color > 0)
    color = 0;
  else
    color = 1;

  imageStore(image, ivec3(gl_GlobalInvocationID), vec4(vec3(color), 1.f));
}

